sudo: false
language: node_js

node_js:
  - "4"
  - "node"

install:
  - npm install -g codecov

script:
  - istanbul cover ./node_modules/lab/bin/lab --report lcovonly  -- -l  && codecov
  - codecov
